In [ ]:
import numpy as np

In [ ]:
a=np.array([2,4,5,6,7])

In [ ]:
a

array([2, 4, 5, 6, 7])

In [ ]:
a.size

5

In [ ]:
a.shape

(5,)

In [ ]:
b=a[1:4]


In [ ]:
b

array([4, 5, 6])

In [ ]:
a[1]


4

In [ ]:
a[2]=100000
a

array([     2,      4, 100000,      6,      7])

In [ ]:
b=[1,2,3,4,5]
c=a+b
c


array([     3,      6, 100003,     10,     12])

In [ ]:
c=2*a
c

array([     4,      8, 200000,     12,     14])

In [ ]:
c=a*b
c

array([     2,      8, 300000,     24,     35])

In [ ]:
c=np.dot(a,b)
c

300069

In [ ]:
a.mean()


20003.8

In [ ]:
np.linspace(12,34,18)

array([12.        , 13.29411765, 14.58823529, 15.88235294, 17.17647059,
       18.47058824, 19.76470588, 21.05882353, 22.35294118, 23.64705882,
       24.94117647, 26.23529412, 27.52941176, 28.82352941, 30.11764706,
       31.41176471, 32.70588235, 34.        ])

In [ ]:
a=np.array([[1,2],[8,3]])
b=np.array([[3,4],[5,6]])


In [ ]:
a

array([[1, 2],
       [8, 3]])

In [ ]:
a[0:2,0:1]

array([[1],
       [8]])

In [ ]:
c=np.dot(a,b)
c

array([[13, 16],
       [39, 50]])